doc의 00-introduction 번역
beewee22/svelte.kr pull request #11
Opened 2019-10-01 05:12 UTC by sukyology

2019-10-01 05:15 UTC, SeongJuMoon commented
이 요청은 #10 PR에 연장선에 있는 내용입니다.

2019-10-01 07:51 UTC, SeongJuMoon approved these changes
보기 좋네요 고생하셨습니다.

2019-10-01 12:07 UTC, beewee22 requested changes
@SeongJuMoon 5번 줄 리뷰와 같이 지켜야 할 마크다운 서식은 glossary에 정리해두는게 좋을 것 같아요

@sukyology 9번줄에 따로 리플을 달지 않았지만 5번 줄 처럼 마크다운 서식을 수정해 주셨으면 좋겠어요~

2019-10-01 12:07 UTC, beewee22 commented on src/content/docs/00-introduction.md
> +> 임시 노트: 이 문서는 현재 진행형입니다. 누락되거나 잘못된 정보가 있어도 양해부탁드리고, 부끄러워하지 마시고 언제든지 채팅으로 도움을 요청하세요. 완성도가 더 높은 건 튜토리얼이니 거기서부터 시작하세요.
채팅으로 도움을 요청하세요
=> [Discord chatroom](채팅)
: 링크로 자동 치환되기 때문에 원본에서의 \[...\](name) 템플릿은 지키는게 좋을 것 같아요.

완성도가 더 높은 건 튜토리얼이니 거기서부터 시작하세요. 
=> 완성도가 더 높은 [tutorial](튜토리얼)부터 시작해 보세요.
: 위와 같은 템플릿 치환 문제를 해결하고, 어색한 번역을 조금 다듬어 보았습니다(권유입니다. 꼭 이대로 바꾸실 필요는 없어요)

2019-10-02 02:39 UTC, SeongJuMoon commented
> @SeongJuMoon 5번 줄 리뷰와 같이 지켜야 할 마크다운 서식은 glossary에 정리해두는게 좋을 것 같아요

좋은 생각인거 같습니다. 지금 처리하도록 하죠.

2019-10-02 03:49 UTC, sukyology commented on src/content/docs/00-introduction.md
> +> 임시 노트: 이 문서는 현재 진행형입니다. 누락되거나 잘못된 정보가 있어도 양해부탁드리고, 부끄러워하지 마시고 언제든지 채팅으로 도움을 요청하세요. 완성도가 더 높은 건 튜토리얼이니 거기서부터 시작하세요.
반영했습니다.

2019-10-04 06:45 UTC, beewee22 approved these changes
고생하셨습니다! 멋져요! 👍 👍

2019-10-04 06:46 UTC, beewee22 commented
@uriyang 리뷰 approve 좀 해주세요 ㅋㅋㅋ

2019-10-05 15:42 UTC, uriyang approved these changes
고생하셨습니다~ 첫 시작을 끊어주셔서 감사합니다. ^^

2019-10-07 04:08 UTC, merged

2019-10-07 05:59 UTC, sukyology commented
오우 리뷰 및 머지 감사합니다. 바빠서 확인이 늦었네요. ㅎㅎ